seml:
  executable: modelTrainFeatures.py
  name: modelTrainFeatures
  output_dir: logs
  project_root_dir: .

slurm:
  - experiments_per_job: 4
    max_simultaneous_jobs: 1  # Restrict number of simultaneously running jobs per job array
    sbatch_options:
      gres: gpu:1       # num GPUs 
      mem: 20G          # memory 
      cpus-per-task: 4  # num cores 
      time: 1-08:00     # max time, D-HH:MM

fixed:
  init.nrFolds: 5
  init.patience: 70
  init.seed_value: 56
  model.batchSize: 100
  model.skipDebugSaves: True # reduces the saved amount of data
  model.saveWeights: False # save model weights or not
  model.dropOutRate: 0.0

  data.dataset: ucr
  data.takename: False #If True, take UTC names rather than numbers
  data.saveMethod: pickle
  data.limit: 700

  model.numEpochs: 500

grid:

  # possible datasets
  data.number:
    # type: range
    # min: 0
    # max: 128
    # step: 1
    type: choice
    options:
      - 1

  data.method:
    type: choice
    options:
      - SFA

  model.architecture:
    type: choice
    options:
      - resnet

  model.symbolCount:
    type: choice
    options:
      - 5
      - 6
  
  model.ncoef:
    type: choice
    options:
      - [128, 2]
      - [256, 1]

  model.strategy:
    type: choice
    options:
      - uniform
      - quantile

  model.num_resblocks:
    type: choice
    options:
      - 3

  model.num_channels:
    type: choice
    options:
      - 16
      - 64
      
  model.use_1x1conv:
    type: choice
    options:
      - True 

  model.lr:
    type: choice
    options:
      - 0.0001
